-- ============================================================
-- BankBank: Tabelle fuer Wanderwege (GPX-Tracks)
-- ============================================================
-- Im Supabase Dashboard des Projekts vsvxkikraedffgvpttnn (bankbank2)
-- unter "SQL Editor" ausfuehren.
--
-- Die Koordinaten werden bereits geparst + ausgeduennt als JSON gespeichert
-- (Array aus [lng, lat]-Paaren), damit die App die Tracks direkt zeichnen
-- kann, ohne GPX-Dateien nachzuladen/zu parsen.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.trails (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  color       text NOT NULL DEFAULT '#d62828',
  points      jsonb NOT NULL,            -- [[lng,lat], [lng,lat], ...]
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.trails ENABLE ROW LEVEL SECURITY;

-- Policies (idempotent neu anlegen) – gleiches Modell wie benches:
-- Lesen fuer alle, Erstellen/Loeschen ueber den anon-Key (Admin-Gating
-- erfolgt clientseitig im Admin-Panel).
DROP POLICY IF EXISTS "Trails are viewable by everyone" ON public.trails;
DROP POLICY IF EXISTS "Anyone can insert trails" ON public.trails;
DROP POLICY IF EXISTS "Anyone can delete trails" ON public.trails;

CREATE POLICY "Trails are viewable by everyone"
  ON public.trails FOR SELECT
  USING (true);

CREATE POLICY "Anyone can insert trails"
  ON public.trails FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Anyone can delete trails"
  ON public.trails FOR DELETE
  USING (true);
